name: CI pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    env:
      CI: true
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        mongodb-version: [4.x, 5.x, 6.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Use MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - run: yarn install
      - run: yarn build
