name: build CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    env:
      CI: true
      NODE_ENV: development
      MONGO_URL: mongodb://localhost:27017/mern-kobol-commerce
    strategy:
      matrix:
        node-version: [14.x, 16.x]
        mongodb-version: [4.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Use MongoDB
        uses: supercharge/mongodb-github-actions@1.7.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - run: yarn install
      - run: yarn build
